### ISSUE TITLE
Update setup instructions and script to account for JS dependencies

### ISSUE THREAD

**Issue by kmeht** [bmun/huxley#304]
Now that we use npm to manage JS dependencies, we should describe that in the setup guide and include it in the setup script.

**Comment by kmeht** [comment]
@nathanielparke we should update this documentation for new developers. Feel free to assign to someone to get this done.

**Comment by nathanielparke** [comment]
@jmosky12 is this something you can take on?

**Comment by jmosky12** [comment]
Absolutely maybe

**Comment by tdowds** [comment]
If there are no objections, I'm gonna close this issue with ed0e2d29008465643e4a60481ff920291c9102c9
@nathanielparke @kmeht
