### ISSUE TITLE
Split out a Registration model from School

### ISSUE THREAD

**Issue by kmeht** [bmun/huxley#331]
Currently, the School model holds two categories of data: the actual school information (name, address, etc.), but also information specific to its registration for a particular session of the conference (number of delegates, country preferences, etc).

We should split this into two models: School, which contains the infrequently-changing school information, and Registration, which depends on School and Conference. This will allow us to build features like registration reactivation, where a school doesn't have to put in their basic information again; they can just update their registration information and re-register immediately!

This will be a pretty non-trivial task, involving at least three migrations, but I think it will be well worth it. I believe that Registration will be the central model of the application, rather than School.

**Comment by kmeht** [comment]
@nathanielparke, note that we'll probably need to add a Conference model before handling this task as well. We can probably make that a separate task.

**Comment by tdowds** [comment]
@m-j-mcdonald pretty sure this is all done now. Let me know if you encounter any bugs from this when getting ready to push to prod or around the time of registration opening up. Also, these PRs would be good for younger members as a learning reference.
