### ISSUE TITLE
Don't fail emails silently

### ISSUE THREAD

**Issue by kmeht** [bmun/huxley#353]
Currently, to avoid borking the request, we have `fail_silently=True` in `send_mail` calls. This is bad because we don't know if the emails are working or not. Instead, we should catch the exception and log or do something so that the tech officer or external officer know what's going on.

More context: https://docs.djangoproject.com/en/dev/topics/email/#send-mail

**Comment by kmeht** [comment]
@tdowds, assigning to you since we have some rudimentary logging set up now :)

**Comment by tdowds** [comment]
Thanks man

**Comment by kmeht** [comment]
Making this high-pri; we should really log this.

**Comment by tdowds** [comment]
Closed via 3b8cab0209f4f0aa8f6ff8ac85aee52b5b3743c5
