### ISSUE TITLE
Assignment Finalization

### ISSUE THREAD

**Issue by vishalkal** [bmun/huxley#361]
On the assignments page, have a checkbox on the side of a row indicating whether or not an advisor wants to keep or remove an assignment. At the bottom, create a button that, upon being clicked, will bring up an agreement stating that this will finalize the assignments they want to keep and permanently give up all the rest.

**Comment by nathanielparke** [comment]
completed via 0c5fe7d03f96a280b1ecdb2dd64f826392bf3ed8
