### ISSUE TITLE
Delegate Name Upload

### ISSUE THREAD

**Issue by vishalkal** [bmun/huxley#382]
In the admin panel, add an 'Upload Delegates' button that will take in a CSV which creates a Delegate object given the names and corresponding assignment.

**Comment by kmeht** [comment]
Shouldn't the advisors be uploading their delegates?

**Comment by vishalkal** [comment]
At least for this year we're collecting names through Google forms and would like to be able to upload them in Huxley.

**Comment by kmeht** [comment]
That's a damn shame. Defeats the entire purpose of Huxley. Why are we using Google forms?

**Comment by vishalkal** [comment]
Conference is moved up so we're cutting it close as is, we're not going to take the risk of trying to build the delegate name feature in time, esp. While the assignment finalization feature is still not finalized
