### ISSUE TITLE
Find a smaller library for async requests

### ISSUE THREAD

**Issue by kmeht** [bmun/huxley#388]
Currently, we're using jQuery to send async requests, but we're trying to break that dependency. So, let's find a library that specializes in async requests and supports our target browsers.

This will help us break our jQuery dependency, tracked in #207.

**Comment by nathanielparke** [comment]
Possibly react-async? https://github.com/andreypopp/react-async

**Comment by kmeht** [comment]
If I understand correctly, that's a library for React components with async data. The one I was looking at was called Reqwest, which is for more generic Async requests.




—

**Comment by kmeht** [comment]
Just learned about the `window.fetch` specification and GitHub's polyfill, which could be exactly what we need: https://github.com/github/fetch

**Comment by kmeht** [comment]
@nathanielparke, @tdowds, might be a good ramp-up task for a new engineer? It has some minor complexities like manually sending cookies (described in the project's README), but shouldn't be too hard.

**Comment by kmeht** [comment]
This would certainly be made easier when all the async calls are in one place after #510.
