### ISSUE TITLE
Create List of Specialized Committees 

### ISSUE THREAD

**Issue by nathanielparke** [bmun/huxley#393]
In the registration view we currently have a section that asks advisors if they would be interested in participating in specialized committees but we do not allow them to choose which specialized committees they want to send delegates to. We should change this so that registration has a list of specialized committees to choose from.

**Comment by kmeht** [comment]
We totally used to have this. Guess we removed it for 63?

**Comment by tdowds** [comment]
Is there more to do on this?

**Comment by kmeht** [comment]
@tdowds, do the list of specialized committees appear on the registration page? That would be the UI portion of this task.

**Comment by tdowds** [comment]
you mean this?
<img width="499" alt="screen shot 2015-07-16 at 9 39 50 pm" src="https://cloud.githubusercontent.com/assets/5726560/8740727/3c87eef0-2c03-11e5-9338-6c09edf72c95.png">

**Comment by kmeht** [comment]
Oh, great! So if registration works correctly (i.e. those preferences are saved), you can close this out.
