### ISSUE TITLE
Invoice generation

### ISSUE THREAD

**Issue by nathanielparke** [bmun/huxley#406]
We are trying to phase out the zoho integration and instead have a cleaner management of the payments workflow. This workflow will be storing the amount of money that the school owes then dynamically generate a PDF invoice upon the user's request. The site admin would be able to keep the amount owed up to date and would give a greater degree of freedom to the admin.

**Comment by nathanielparke** [comment]
http://www.reportlab.com/

https://docs.djangoproject.com/en/1.8/howto/outputting-pdf/

Initial ideas for the tool that can be used

**Comment by nathanielparke** [comment]
http://stackoverflow.com/questions/1377446/render-html-to-pdf-in-django-site

**Comment by nathanielparke** [comment]
![invoice template](https://cloud.githubusercontent.com/assets/5566646/9707280/35fb875e-54b7-11e5-96e5-936daf41b81d.png)

**Comment by kmeht** [comment]
Is that an actual screenshot of a generated PDF? That's dope.

**Comment by nathanielparke** [comment]
That is the sample we are trying to emulate Currently we have "Hello, World" working.

**Comment by tdowds** [comment]
@nathanielparke is there more we need to do on this?

**Comment by nathanielparke** [comment]
Nope! This is good. Just forgot to close this issue.
