### ISSUE TITLE
Use standard Flux

### ISSUE THREAD

**Issue by kmeht** [bmun/huxley#409]
Right now we're using the toy examples in the Flux documentation as our Flux implementation. We should instead use the standard open-sourced version in http://www.github.com/facebook/flux.

**Comment by kmeht** [comment]
@tdowds, I started this a little bit with CurrentUserStore, so we already have the Flux dependencies loaded. Take a look at my previous commits to check out how I went about it.

**Comment by tdowds** [comment]
closed via #449
