### ISSUE TITLE
Too Many delegates Causes overflow error

### ISSUE THREAD

**Issue by nathanielparke** [bmun/huxley#411]
We may or may not want to look into this but if a user puts in an extraordinary amount of delegates we get an error on the backend. Error will follow in a comment.

**Comment by nathanielparke** [comment]
InvalidOperation: quantize result has too many digits for current context

**Comment by kmeht** [comment]
How's this going? Should be pretty easy to cap the number of delegates on both the client and server validation.

**Comment by m-j-mcdonald** [comment]
This should be a good first task for you Jacky, it'll help you get familiar with Django a bit
