### ISSUE TITLE
Create a way to better deal with CSV upload failures for Assignments

### ISSUE THREAD

**Issue by nathanielparke** [bmun/huxley#432]
Currently if an assignment upload cannot find a Country, Committee or School when using the bulk CSV upload tool the entire upload fails. We should build a feature that stores the rows that fail into a separate CSV, uploads the assignments that are valid and return the failure CSV to the user.

**Comment by tdowds** [comment]
closed via 774a7540ec60fe690d5d2929eac23717176f94aa
