### ISSUE TITLE
# of Chinese & Spanish speaking delegates can exceed total # of delegates

### ISSUE THREAD

**Issue by m-j-mcdonald** [bmun/huxley#439]
In the registration view the user can input a number of delegates that speak chinese or spanish that exceeds the total numbers of delegates they previously inputted as attending.

**Comment by kmeht** [comment]
Do we have clientside validation? Otherwise, it should be possible to update the serverside validators to handle this.

**Comment by nathanielparke** [comment]
@m-j-mcdonald we have both clientside and serverside validators which we should utilize both of. You can see an example of the clientside validation with the password inputs in the registration view. Server side would be the school serializer in the api.

**Comment by kmeht** [comment]
Fixed by #483.
