### ISSUE TITLE
Upgrade to Django 1.8

### ISSUE THREAD

**Issue by kmeht** [bmun/huxley#443]
Let's keep our codebase up-to-date; there should only be a few, if any, breaking changes for this upgrade.

**Comment by kmeht** [comment]
(I know that Django 1.9 is out, but updating sequentially is easier than skipping versions).

**Comment by kmeht** [comment]
@nathanielparke sorry, I didn't catch that you self-assigned this! I'm just about to commit this.

**Comment by nathanielparke** [comment]
No worries! I will get the next one!
