### ISSUE TITLE
Automate Closing Registration

### ISSUE THREAD

**Issue by nathanielparke** [bmun/huxley#446]
The current way to close registration is to manually change the browserify-ed static file. This is clunky and should be changed. There are a couple ways of doing this. The first is to use the Registration.py file to change the setting. The second is to use the admin panel to propagate the changes.

**Comment by nathanielparke** [comment]
Lets bundle all the tasks associated with this into a Fabric script. I think building out a

    fab registration: open / close / waitlist

command would be relevant and useful. It should automatically interface with the settings files to abstract 
that away from a server admin.

**Comment by kmeht** [comment]
Really, this shouldn't be part of a settings file. Preferably, it would be a field in the Conference model (when we actually start using that).

**Comment by nathanielparke** [comment]
https://github.com/bmun/huxley/pull/471

**Comment by nathanielparke** [comment]
0d6af31a2313f870c7be41449e3b2c11ed87d012
