### ISSUE TITLE
Update amount owed when external inputs a value for amount paid

### ISSUE THREAD

**Issue by tdowds** [bmun/huxley#453]
Currently on the admin panel if external wants to update the amount a school owes it has to go in and change the number of delegates so that the model recalculates how much the school owes. What we should do instead is input how much that school has paid on the admin panel so that the amount owed is reduced by how much has been paid.

**Comment by nathanielparke** [comment]
Also relates to #457 so that the cost per delegate is managed by the conference model

**Comment by tdowds** [comment]
@michaeleliot when you go onto the admin panel the total fees field appears when you look at a school. Can you get rid of it?

**Comment by tdowds** [comment]
Closed via 70a0f8c3e44b32ede3c5a25717878af8252bfdc5
