### ISSUE TITLE
Update easy_pdf To Reflect Django 1.8 template usage

### ISSUE THREAD

**Issue by nathanielparke** [bmun/huxley#456]
https://docs.djangoproject.com/en/1.9/ref/templates/upgrading/

We use the Context model to render our PDFs. easy_pdf should have an update that allows for this new flow. Making this issue to investigate so I don't forget about it.

**Comment by kmeht** [comment]
@nathanielparke could you elaborate on this task? Maybe link to easy_pdf documentation that indicates what updates need to be made?

**Comment by kmeht** [comment]
Seems like we just have to switch from `render_to_pdf_response` to implementing a `get_context_data` method: http://django-easy-pdf.readthedocs.io/en/latest/usage.html#create-pdf-rendering-views
