### ISSUE TITLE
Add Conference Dependent Data to Conference Model

### ISSUE THREAD

**Issue by nathanielparke** [bmun/huxley#457]
We should add in things like current Secretary General, Current External, the price per delegate for the current year etc. to the conference model so it can all be tracked through the admin panel and none of that is hard coded. This will require propagating the data through to things such as the AdvisorProfileView using Flux

**Comment by tdowds** [comment]
Todos for this:
- [ ] Propagate start and end date to LoginView
- [ ] Propagate name of external to AdvisorProfileView and RegistrationSuccessView
- [ ] Propagate fees to RegistrationSuccessView
- [ ] Use fees in School model
- [ ] Use session in email confirmation

**Comment by tdowds** [comment]
Closed via 1507f8e836677805874fcf11bf3ffa5eabd709d9
