### ISSUE TITLE
Add Logging

### ISSUE THREAD

**Issue by kmeht** [bmun/huxley#46]
Develop a system of logging to be used throughout the app. I am way over seeing a 500 internal server error and then bending over backward to debug it. We should write clear, concise, descriptive logs throughout the app's execution.

Subtasks:
- [x] Add a basic console logger
- [x] Log exceptions
- [x] Add log statements tracking the lifecycle of requests
- [x] Create a `logging` app with a `LogEntry` model
- [x] Set up log settings to log to console in dev, and log to `logging` in stage/production

**Comment by tdowds** [comment]
closed via 3d94ccbb26c72c4a77db14505c713ab2bf329504
