### ISSUE TITLE
AdvisorRosterView

### ISSUE THREAD

**Issue by nathanielparke** [bmun/huxley#462]
This view will be where advisors can create delegates and manage their delegate list. Feature that will be in the page are
- [x] Delegate Creation
- [x] Linking of Assignment to Delegate
- [x] Delegate Deletion
- [ ] Chair comments viewing
- [ ] TENATIVE: Waiver signing

The view will be the portal for advisors oversee their delegate's experience in conference as well as track how delegates are doing in committee.

**Comment by tdowds** [comment]
This would be a really good introduction to the front end and connecting it with our API for those unfamiliar with Huxley

**Comment by tdowds** [comment]
Given what Nate has done, these are things you're going to need to do:
- [ ] Update the nav bar to include "Roster" link
- [ ] Add the functionality to add a delegate (So a button and text input fields)
- [ ] Make a request to our API to add the delegate
- [ ] Add the functionality to delete a delegate (A button of some sort)
- [ ] Make a request to our API to delete the delegate
- [ ] Add the functionality to update a delegate 
- [ ] Make a request to our API to update the delegate
- [ ] In AdvisorAssignmentView add a dropdown for each assignment that lists delegates to be assigned to it
- [ ] Don't allow a delegate to be assigned to more than one assignment
Some conversation will need to be had later on to decide how to handle to assigning one delegate to a double delegate assignment, but we should split that out into a different task

**Comment by nathanielparke** [comment]
@jmosky12 What is the status on this?

**Comment by tdowds** [comment]
Let's close this out for now. And add on the chair's comments and attendance once we build the chair app back out.

Closed via 4ad41c27f04750b4603f24f01440b760d29f8bfa
