### ISSUE TITLE
Make School Registration Information Mutable

### ISSUE THREAD

**Issue by nathanielparke** [bmun/huxley#463]
Currently the AdvisorProfileView does not allow for advisors to edit the data that they registered with. This should be changed. We should create a button at the top of the data view that allows for an advisor to edit the data then save or discard the edit. In the backend we should also add a tag that signifies when the data was last updated. This is so that External will know if their information for a given school is out of date.

**Comment by tdowds** [comment]
@michaeleliot if memory serves me right, the way we use to do this was whenever the cursor hovered over one of the fields it would highlight. Then you could click on the field to update the text. Then you would hit a save button to submit those changes. So one possible approach would be to take it in these chunks: 

- [ ] Highlight table cell on hover
- [ ] Clicking a cell creates a textbox in which to edit the information
- [ ] Changing focus away from the cell restores it to its normal state
- [ ] Add save button
- [ ] Make a request to our API to save those changes

**Comment by nathanielparke** [comment]
@michaeleliot Per discussion with @tdowds we realized that editing data of a school can cause some logistical problems for external. The issue is that when an advisor changes their info if we silently allow them to change the data and don't notify external then there is a data inconsistency between what data external is using and the data that is in our DB. 

Potential fixes to this:

1. Change log for external to review when accessing the admin panel
2. Send a [Insert time length here] digest email to external of all the data that was changed
3. Send an email to external every time data is changed

Feel free to PM myself or Trevor with questions.

**Comment by kmeht** [comment]
@nathanielparke, why does external use a different version of school data than our DB? Isn't that the whole problem Huxley was supposed to solve? Is there a way we can solve this deeper problem?

**Comment by tdowds** [comment]
Discussed this with external here are the specifications for this task:
Fields enabled to be changed:
* Advisor Information
 * First Name
 * Last Name
* School Information
 * Address
 * City
 * Zip
* Primary Contact Information & Secondary Contact Information
 * Name
 * Email
 * Phone

Like @nathanielparke said, external needs to be notified if there's a change, therefore on a successful change we're going to send external an email.

@michaeleliot this task is good to go if you want to start working on it (I had told him to hold off cause external was hesitant about doing this).

@kmeht I believe external downloads data from Huxley but if a change is made without external knowing, she could be using inconsistent information (like an incorrect email).

**Comment by nathanielparke** [comment]
fixed in 1bcb28149f503c7f8fc212ba120ace94b96823b9
