### ISSUE TITLE
Introduce autoformatters into the workflow

### ISSUE THREAD

**Issue by kmeht** [bmun/huxley#472]
There are automatic code format tools that should help us avoid wasting code review cycles on style nits. One example is [`autopep8`](https://pypi.python.org/pypi/autopep8) for Python.

I believe it has an option to specify line numbers, so we could write a Fabric command to detect the changed lines in a Python file, and run the autoformatter on it. This would help us move faster in development and code review.

**Comment by nathanielparke** [comment]
Another possible one is https://github.com/google/yapf
