### ISSUE TITLE
Switch to More Logical Git Workflow

### ISSUE THREAD

**Issue by nathanielparke** [bmun/huxley#487]
The current workflow that we have right now does not allow us to manage releases effectively. By operating our code out of one production branch, namely master, we aren't allowing any way to check in features that we want to centralize but not have in production. One alternative to this is to create a second branch, named 'develop' that is the most recent version of the code that the developers develop against. This moves the master branch to being the production ready code that can be deployed on the server. When the time comes where the 'develop' branch is at a point stable enough for a production release we then merge the develop branch into master. This issue will track the change to this flow and will require some changes to the fabric files that we use to manage tasks like this. 

http://nvie.com/posts/a-successful-git-branching-model/

That is what I have based this thought off of.

**Comment by kmeht** [comment]
What if there's a feature that requires long-term development (e.g. many PRs), but another feature is developed that needs to be deployed? Either we'll need to cherrypick the feature into the release branch, or just have many development branches. The Fabfile will have to be updated to handle this, or everyone will have to become really comfortable with git.

I'm wondering about the tradeoffs of complicating our workflow vs. the utility we'll gain from it.

**Comment by nathanielparke** [comment]
I think one way to deal with that is through branches that the article names 'hotfixes'. The idea being that if there is some change that absolutely needs to get into the production code then we can make an exception and merge it directly. I agree though I think this is strategy would be nice for development during open registration.
