### ISSUE TITLE
Deleting delegates doesn't update client store

### ISSUE THREAD

**Issue by kmeht** [bmun/huxley#518]
When we delete a delegate, the clientside store isn't updated.

Repro steps:
- On roster page, delete a delegate
- Switch to another page and back
- See that the delegate is still there (note that on refresh, the delegate is gone).

This is because we're not following Flux well. In the roster view, we should be dispatching an action that both sends the server API request and also removes the delegate from the clientside store.

**Comment by kmeht** [comment]
@tdowds, this is one specific case of #523.

**Comment by tdowds** [comment]
Closed via 408addb76ca7393c771af666c2a4a7d85dfed508
