### ISSUE TITLE
Fix text input on refocus

### ISSUE THREAD

**Issue by m-j-mcdonald** [bmun/huxley#519]
Right now there's an issue where every time a character is entered into an input box the focus shifts to the end of the line immediately after registering the keystroke. So if someone tries to go back and edit part of what they were typing, only a single character will go where they want it and the rest of the keystrokes will be registered at the end of the text. E.g., if someone was typing "2700 Avenue" and realized it should have Durant in there, it would come out as "2700 DAvenueurant " when they tried to fix it.

**Comment by kmeht** [comment]
Bunch of discussion here, maybe it'll be useful: https://github.com/facebook/react/issues/955
