### ISSUE TITLE
Where to deploy?

### ISSUE THREAD

**Issue by ojas121** [bmun/huxley#521]
I've looked at a few PaaS to deploy huxley, but it hasn't been working.
Could you tell me what the requirements are, and if you have any specific platforms that you'd recommend?

**Comment by kmeht** [comment]
We use Webfaction (a simple web host) to deploy Huxley. Here's a guide: https://github.com/bmun/huxley/blob/master/docs/deploy/WEBFACTION.md

We haven't tried deploying on any other services, so if you successfully deploy elsewhere, please consider contributing a guide! We'd appreciate it.
