### ISSUE TITLE
Use Flux for data updates

### ISSUE THREAD

**Issue by kmeht** [bmun/huxley#523]
In many places, such as AdvisorAssignmentsView, we are updating the component's state directly and then "refreshing" by navigating to the same page to update.

Instead, we should:
- subscribe to the Stores in the component
- update the data in the Stores via Actions
- then, the component will re-render automatically in response to the changed data.

This will require adding Actions for each type of data update, and updating the Stores to handle such actions. Admittedly, this is a bunch of boilerplate for a small app. But, it will help the app scale as we add more and more features.

**Comment by tdowds** [comment]
Things to do:
- [ ] Use flux for Delegates
- [ ] Use flux for Assignments
- [ ] Fire actions in response to successful saves or errors from the server
- [ ] Use flux to get committees and countries(?)
