### ISSUE TITLE
Split up RegistrationView into subcomponents

### ISSUE THREAD

**Issue by kmeht** [bmun/huxley#529]
This component is huge. Let's split it up into sections for sanity. This will also allow for some perf optimizations later, where we can avoid re-rendering an entire section if any of its properties haven't changed.

**Comment by tdowds** [comment]
@jaketibbetts this should be a good task to get you some more experience working with React

**Comment by tdowds** [comment]
Closing this via 69333ee84f24d8246a70c08c51b351171f5f6fa5 if there are no exceptions.
