### ISSUE TITLE
Admin panel broken w/Django 1.9 switch

### ISSUE THREAD

**Issue by m-j-mcdonald** [bmun/huxley#557]
This line is causing the admin panels for the core models to fail: {% load url from future %}. Apparently it was removed in Django 1.9.

Here is what I get trying to access any panel from core:
<img width="1280" alt="screen shot 2017-01-07 at 6 55 56 pm" src="https://cloud.githubusercontent.com/assets/14935470/21746945/7193c260-d50b-11e6-8eef-4b65f1ada6fc.png">
<img width="1280" alt="screen shot 2017-01-07 at 6 56 08 pm" src="https://cloud.githubusercontent.com/assets/14935470/21746946/71c47680-d50b-11e6-9085-e203ad9a5678.png">

**Comment by kmeht** [comment]
This was deprecated in 1.7 and we somehow just missed it. It appears we can simply remove them: https://docs.djangoproject.com/en/1.10/releases/1.7/#loading-ssi-and-url-template-tags-from-future-library

/cc @patilpranay
