### ISSUE TITLE
Delegate Accounts

### ISSUE THREAD

**Issue by m-j-mcdonald** [bmun/huxley#614]
It's time we put delegate accounts into Huxley. The objective is two fold: the primary aspect being that I intend to incorporate position paper grading into Huxley, and before that begins delegates will need a portal to access Huxley. But also, it gives us a better way to route feedback from conference and provide a general interface for interaction with delegates.

Here is a general overview to track the progress for these:
- [x] Update the backend model and api
- [x] Add initial frontend views as well as stores, actions, and routing
- [x] Create accounts when assignments are finalized
- [x] Delete accounts with delegates

**Comment by kmeht** [comment]
@m-j-mcdonald I imagine deletion is also a part of this, yeah? Since advisors can not only add but delete delegates, we should delete the accounts as well.

**Comment by m-j-mcdonald** [comment]
I don't think deletion is a huge concern, since advisors can't remove delegates once they have finalized their rosters (which happens before they finalize their assignments). That's part of why I designed he account creation to happen when assignments are finalized.
