### ISSUE TITLE
Delegate delete quirk

### ISSUE THREAD

**Issue by m-j-mcdonald** [bmun/huxley#626]
When an advisor delete's a delegate the action succeeds but this is displayed anyways:

<img width="1280" alt="screen shot 2017-09-15 at 4 58 14 pm" src="https://user-images.githubusercontent.com/14935470/30507321-265d12fe-9a38-11e7-8fa3-f9dcd54371a4.png">

**Comment by kmeht** [comment]
There's also a grammar mistake, lol.

**Comment by shaynak** [comment]
will be resolved by upcoming stage merge
