### ISSUE TITLE
Assignment admin needs to be modified to use registration model 

### ISSUE THREAD

**Issue by m-j-mcdonald** [bmun/huxley#627]
core/admin/assignment.py was never updated to reflect the registration model; just putting this as a reminder we need to do that before External tries to upload assignments

**Comment by tdowds** [comment]
Ahh my bad, I can take this if it'll help you out

**Comment by m-j-mcdonald** [comment]
If you're willing to that'd be great; it'd be a good task for a newer member but I don't think we want to wait that long to push up the fix
