### ISSUE TITLE
Design Better System for Enabling/Disabling Features

### ISSUE THREAD

**Issue by m-j-mcdonald** [bmun/huxley#632]
Putting this here so we don't forget about it. Right now we enable/disable features such as registration or delegate selection by manually commenting out code or disabling options. We should come up with a more elegant way of handling features that are only active during certain times.

**Comment by m-j-mcdonald** [comment]
There's a new utility function in huxley/www/js/utils/_checkDate.js that should help handle this. I already put into most of the Advisor pages

**Comment by shaynak** [comment]
closing issue, mostly fixed via #718
