### ISSUE TITLE
Prevent upload of country that already exists

### ISSUE THREAD

**Issue by mathildepm** [bmun/huxley#720]
Currently, Huxley allows two countries to have the same name (if one is special and the other is not, it accepts it). This causes errors when assignments are uploaded later on. Change this such that no two countries can have the same name.

1. You can set the field of country name to be unique: https://docs.djangoproject.com/en/dev/ref/models/fields/#unique

Since you changed models.py, you'll have to make and apply migrations (see a description of how to do migrations in [Working with Huxley](https://docs.google.com/document/d/1RiXcZlAlKDXiyNhDeKmLs6n1uk6lCDOqWyLT48bJ0n4/edit?usp=sharing) section for adding a field to a model) 

2. Test by running a local server and trying to manually add a country with a name that already exists. It should error. Should also try uploading a csv and making sure it errors if the csv contains countries that already exist. 

3. Since we don't want an ugly error to happen on a csv upload, we want a nice little html error that simply tells admin which countries were not uploaded because they already exist. 
Modify the load function at **/huxley/core/admin/country.py** such that it doesn't try to save a country with a name that already exists (look into try/catch suites), instead it should keep a running list of all the countries that were skipped and if any were skipped, at the end output an error message with relevant information. You can base this error message off the one at the end of the load function in **/huxley/core/admin/assignment.py**

4. Test again by uploading a csv and seeing if it works!

**Comment by erwang01** [comment]
Modifying models.py:69-77

```
class Country(models.Model):
    name = models.CharField(max_length=128)
    special = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = u'country'
```

Questions: 
- What is "Special"?

**Comment by erwang01** [comment]
Everything works now, need Unittest update, 31 errors.
