### ISSUE TITLE
Prevent Assignment Overwrites 

### ISSUE THREAD

**Issue by mathildepm** [bmun/huxley#748]
Admin assigns Country A to School 1 by uploading a sheet. 
School 1 accepts. 
Admin assigns Country A to School 2 by uploading a different sheet
School 2 accepts. 

School 1 lost their assignment and no one knew!!! 

Change assignment uploads to flag and prevent assignment overwrites (unless, assignment has already been rejected by school 1)

**Comment by michaelvdang** [comment]
Hi is this issue still open? I'd like to contribute. And please let me know where to start. Thank you!

**Comment by mathildepm** [comment]
@michaelvdang thanks for your offer, but we realized this wasn't a starter issue after all!
