### ISSUE TITLE
Add CSV formatting instructions in CSV load blurbs for Admin

### ISSUE THREAD

**Issue by mathildepm** [bmun/huxley#759]
<img width="491" alt="Screen Shot 2021-06-24 at 7 43 34 PM" src="https://user-images.githubusercontent.com/46112084/123361764-7a295480-d524-11eb-9a0b-bab98951f220.png">
For Countries, Secretariat Member, Assignments and any other class that has a load function, there are no clear instructions for how to format a csv before uploading. 

It would be very beneficial to update the admin view of django such that in the main admin panel for each of these models, near the "Upload File" button, there is a description for the format of the csv (type of csv, number of columns and what values they can have, etc). If the description button gets too long, maybe hide it under a button. 

This will probably require some research into changing the django admin view but is mostly text so should not be too difficult!

**Comment by erwang01** [comment]
Do we have samples of the file format?

**Comment by erwang01** [comment]
alternative is to search via core/admin/blah.py but thats a pain :(

**Comment by erwang01** [comment]
Also probably good idea to have a single source of truth...

**Comment by erwang01** [comment]
For now I just left comments saying to remember to change the change_list.html on the cord/admin/blah.py scripts.

> Also probably good idea to have a single source of truth...
